# Uncomment the next line to define a global platform for your project

platform :ios, '7.0'

target 'MWPhotoBrowser_Example' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MWPhotoBrowser_Example

  pod "MWPhotoBrowser", :path => "../"

end

